import { Location, Printer, PrinterType, Status } from '@/types/printer';

export const printers: Printer[] = [
  {
    id: 1,
    name: 'HCMUT-SSPS 1',
    status: Status.GOOD,
    type: PrinterType.CANON,
    location: Location.A2_CS1,
    paperAvailable: 110,
  },
  {
    id: 2,
    name: 'HCMUT-SSPS 2',
    status: Status.STOPPED,
    type: PrinterType.HP,
    location: Location.A3_CS1,
    paperAvailable: 80,
  },
  {
    id: 3,
    name: 'HCMUT-SSPS 3',
    status: Status.GOOD,
    type: PrinterType.EPSON,
    location: Location.A2_CS1,
    paperAvailable: 120,
  },
  {
    id: 4,
    name: 'HCMUT-SSPS 4A',
    status: Status.GOOD,
    type: PrinterType.HP,
    location: Location.A4_CS1,
    paperAvailable: 90,
  },
  {
    id: 5,
    name: 'HCMUT-SSPS 4B',
    status: Status.GOOD,
    type: PrinterType.CANON,
    location: Location.B1_CS1,
    paperAvailable: 110,
  },
  {
    id: 6,
    name: 'HCMUT-SSPS 5',
    status: Status.STOPPED,
    type: PrinterType.HP,
    location: Location.B2_CS1,
    paperAvailable: 70,
  },
  {
    id: 7,
    name: 'HCMUT-SSPS 6',
    status: Status.GOOD,
    type: PrinterType.EPSON,
    location: Location.B1_CS1,
    paperAvailable: 130,
  },
  {
    id: 8,
    name: 'HCMUT-SSPS 7',
    status: Status.GOOD,
    type: PrinterType.HP,
    location: Location.B12_CS1,
    paperAvailable: 60,
  },
  {
    id: 9,
    name: 'HCMUT-SSPS 8',
    status: Status.GOOD,
    type: PrinterType.CANON,
    location: Location.C1_CS1,
    paperAvailable: 100,
  },
  {
    id: 10,
    name: 'HCMUT-SSPS 9',
    status: Status.STOPPED,
    type: PrinterType.HP,
    location: Location.C4_CS1,
    paperAvailable: 85,
  },
  {
    id: 11,
    name: 'HCMUT-SSPS 11A',
    status: Status.GOOD,
    type: PrinterType.EPSON,
    location: Location.C5_CS1,
    paperAvailable: 95,
  },
  {
    id: 12,
    name: 'HCMUT-SSPS 11B',
    status: Status.GOOD,
    type: PrinterType.EPSON,
    location: Location.C6_CS1,
    paperAvailable: 105,
  },
  {
    id: 13,
    name: 'HCMUT-SSPS 12',
    status: Status.GOOD,
    type: PrinterType.CANON,
    location: Location.C5_CS1,
    paperAvailable: 115,
  },
  {
    id: 14,
    name: 'HCMUT-SSPS XX',
    status: Status.GOOD,
    type: PrinterType.CANON,
    location: Location.A2_CS1,
    paperAvailable: 0,
  },
];
