/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './features/~__root'
import { Route as IndexImport } from './features/~index'
import { Route as SignupIndexImport } from './features/~signup/~index'
import { Route as LoginIndexImport } from './features/~login/~index'
import { Route as HomeIndexImport } from './features/~home/~index'
import { Route as AdminIndexImport } from './features/~admin/~index'
import { Route as AdminUserIndexImport } from './features/~admin/~user/~index'
import { Route as AdminTagIndexImport } from './features/~admin/~tag/~index'
import { Route as AdminCommentIndexImport } from './features/~admin/~comment/~index'
import { Route as AdminArticleIndexImport } from './features/~admin/~article/~index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUserIndexRoute = AdminUserIndexImport.update({
  id: '/admin/user/',
  path: '/admin/user/',
  getParentRoute: () => rootRoute,
} as any)

const AdminTagIndexRoute = AdminTagIndexImport.update({
  id: '/admin/tag/',
  path: '/admin/tag/',
  getParentRoute: () => rootRoute,
} as any)

const AdminCommentIndexRoute = AdminCommentIndexImport.update({
  id: '/admin/comment/',
  path: '/admin/comment/',
  getParentRoute: () => rootRoute,
} as any)

const AdminArticleIndexRoute = AdminArticleIndexImport.update({
  id: '/admin/article/',
  path: '/admin/article/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/article/': {
      id: '/admin/article/'
      path: '/admin/article'
      fullPath: '/admin/article'
      preLoaderRoute: typeof AdminArticleIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/comment/': {
      id: '/admin/comment/'
      path: '/admin/comment'
      fullPath: '/admin/comment'
      preLoaderRoute: typeof AdminCommentIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tag/': {
      id: '/admin/tag/'
      path: '/admin/tag'
      fullPath: '/admin/tag'
      preLoaderRoute: typeof AdminTagIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/admin/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/admin/article': typeof AdminArticleIndexRoute
  '/admin/comment': typeof AdminCommentIndexRoute
  '/admin/tag': typeof AdminTagIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/admin/article': typeof AdminArticleIndexRoute
  '/admin/comment': typeof AdminCommentIndexRoute
  '/admin/tag': typeof AdminTagIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/admin/article/': typeof AdminArticleIndexRoute
  '/admin/comment/': typeof AdminCommentIndexRoute
  '/admin/tag/': typeof AdminTagIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/login'
    | '/signup'
    | '/admin/article'
    | '/admin/comment'
    | '/admin/tag'
    | '/admin/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/home'
    | '/login'
    | '/signup'
    | '/admin/article'
    | '/admin/comment'
    | '/admin/tag'
    | '/admin/user'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/home/'
    | '/login/'
    | '/signup/'
    | '/admin/article/'
    | '/admin/comment/'
    | '/admin/tag/'
    | '/admin/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  AdminArticleIndexRoute: typeof AdminArticleIndexRoute
  AdminCommentIndexRoute: typeof AdminCommentIndexRoute
  AdminTagIndexRoute: typeof AdminTagIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  AdminArticleIndexRoute: AdminArticleIndexRoute,
  AdminCommentIndexRoute: AdminCommentIndexRoute,
  AdminTagIndexRoute: AdminTagIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/admin/",
        "/home/",
        "/login/",
        "/signup/",
        "/admin/article/",
        "/admin/comment/",
        "/admin/tag/",
        "/admin/user/"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/admin/": {
      "filePath": "~admin/~index.tsx"
    },
    "/home/": {
      "filePath": "~home/~index.tsx"
    },
    "/login/": {
      "filePath": "~login/~index.tsx"
    },
    "/signup/": {
      "filePath": "~signup/~index.tsx"
    },
    "/admin/article/": {
      "filePath": "~admin/~article/~index.tsx"
    },
    "/admin/comment/": {
      "filePath": "~admin/~comment/~index.tsx"
    },
    "/admin/tag/": {
      "filePath": "~admin/~tag/~index.tsx"
    },
    "/admin/user/": {
      "filePath": "~admin/~user/~index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
